import "./globals.css";
import type { Metadata } from "next";
import {
  Inter,
  Playfair_Display,
  Zen_Kaku_Gothic_Antique,
} from "next/font/google";

import Provider from "./provider/provider";

export const zen = Zen_Kaku_Gothic_Antique({
  subsets: ["latin"],
  weight: "500",
});
export const play = Playfair_Display({ subsets: ["latin"] });

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "login & signup",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
